---
- name: Import install tasks
  import_tasks: install.yml

- name: Import base tasks
  import_tasks: base.yml

- name: Import repository tasks
  include_tasks: repository/main.yml
  loop: "{{ aptly__repositories | flatten(levels=1) }}"
  loop_control:
    loop_var: aptly__repository
