---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Get release file
      ansible.builtin.get_url:
        validate_certs: false
        url: http://127.0.0.1/apt/dists/jammy/Release.gpg
        dest: /tmp/Test